#!/usr/bin/env python3
"""Write firmware_avrdd/pinmap.h from layout.py.

    python3 gen_avrdd_pinmap.py

For every console layout the header lists which RetroPad bit each of the 13
button slots carries (slot order = the layout's button order). The firmware
reads the console ID from its straps and picks the matching row, so one
firmware image serves every AVR DD board. gen_pcb.py wires the same slots.
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(HERE))
import layout  # noqa: E402

OUT = os.path.join(HERE, "..", "..", "firmware_avrdd", "pinmap.h")

# Console IDs without a layout (generic, Atari, PCE, Neo Geo, ...) still get a
# full row, so no slot can fall back to 0 (= RP_BTN_UP): this generic order.
GENERIC = ["UP", "DOWN", "LEFT", "RIGHT", "A", "B", "X", "Y", "L", "R", "SELECT", "START", "MENU"]


def main():
    by_id = {}
    for name, (cid, title) in layout.CONSOLES.items():
        if name.endswith("_dd"):
            continue                     # same layout as its base console
        by_id[cid] = (name, title, layout.avrdd_slots(name))

    lines = [
        "/* Generated by boards/kicad_gen/gen_avrdd_pinmap.py from boards/layout.py. Do not edit. */",
        "#ifndef RETROPAD_PINMAP_H",
        "#define RETROPAD_PINMAP_H",
        "",
        "#include <avr/io.h>",
        '#include "retropad_proto.h"',
        "",
        "#define SLOT_COUNT %d" % len(layout.AVRDD_SLOTS),
        "#define SLOT_NONE  0xFF",
        "",
        "/* Button slot -> MCU pin (switch to GND, internal pull-up) */",
        "static PORT_t *const slot_port[SLOT_COUNT] = {%s};" % ", ".join("&PORT%s" % p[1] for p in layout.AVRDD_SLOTS),
        "static const uint8_t slot_pin[SLOT_COUNT] = {%s};" % ", ".join(p[2] for p in layout.AVRDD_SLOTS),
        "",
        "/* Console ID -> RetroPad bit carried by each slot (SLOT_NONE = not fitted) */",
        "static const uint8_t slot_bit[RP_CONSOLE_COUNT][SLOT_COUNT] = {",
    ]
    for cid in range(16):
        if cid in by_id:
            name, title, slots = by_id[cid]
            bits = ["RP_BTN_%s" % rp[len("RP_BTN_"):] for _, rp, _ in slots]
            bits += ["SLOT_NONE"] * (len(layout.AVRDD_SLOTS) - len(bits))
            names = ", ".join("%s=%s" % (b, pin) for b, _, pin in slots)
            lines.append("    /* %2d %s: %s */" % (cid, title, names))
        else:
            bits = ["RP_BTN_" + b for b in GENERIC]
            lines.append("    /* %2d no AVR DD layout yet: generic slot order %s */" % (cid, " ".join(GENERIC)))
        lines.append("    [%d] = {%s}," % (cid, ", ".join(bits)))
    lines += ["};", "", "#endif /* RETROPAD_PINMAP_H */", ""]
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("\n".join(lines))
    print("wrote", os.path.normpath(OUT))


if __name__ == "__main__":
    main()
