#!/usr/bin/env python3
"""Write firmware_avrdd/pinmap.h from layout.py.

    python3 gen_avrdd_pinmap.py

For every console layout the header lists which RetroPad bit each of the 13
button slots carries (slot order = the layout's button order). The firmware
reads the console ID from its straps and picks the matching row, so one
firmware image serves every board. gen_pcb.py wires the same slots.
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(HERE))
import layout  # noqa: E402

OUT = os.path.join(HERE, "..", "..", "firmware_avrdd", "pinmap.h")

# Console IDs without a layout (generic, Atari, PCE, Neo Geo, ...) still get a
# full row, so no slot can fall back to 0 (= RP_BTN_UP): this generic order.
# Status LED brightness (0-255) for the console-select colours
LED_LEVEL = 40

GENERIC = ["UP", "DOWN", "LEFT", "RIGHT", "A", "B", "X", "Y", "L", "R", "SELECT", "START", "MENU"]


def main():
    by_id = {}
    for name, (cid, title) in layout.CONSOLES.items():
        by_id[cid] = (name, title, layout.avrdd_slots(name))
    for cid, name in layout.ALIASES.items():
        title = "same slots as the %s board" % layout.CONSOLES[name][1]
        by_id.setdefault(cid, (name, title, layout.avrdd_slots(name)))

    lines = [
        "/* Generated by boards/kicad_gen/gen_avrdd_pinmap.py from boards/layout.py. Do not edit. */",
        "#ifndef RETROPAD_PINMAP_H",
        "#define RETROPAD_PINMAP_H",
        "",
        "#include <avr/io.h>",
        '#include "retropad_proto.h"',
        "",
        "#define SLOT_COUNT %d" % len(layout.AVRDD_SLOTS),
        "#define SLOT_NONE  0xFF",
        "",
        "/* Button slot -> MCU pin (switch to GND, internal pull-up) */",
        "static PORT_t *const slot_port[SLOT_COUNT] = {%s};" % ", ".join("&PORT%s" % p[1] for p in layout.AVRDD_SLOTS),
        "static const uint8_t slot_pin[SLOT_COUNT] = {%s};" % ", ".join(p[2] for p in layout.AVRDD_SLOTS),
        "",
        "/* Console ID -> RetroPad bit carried by each slot (SLOT_NONE = not fitted) */",
        "static const uint8_t slot_bit[RP_CONSOLE_COUNT][SLOT_COUNT] = {",
    ]
    for cid in range(16):
        if cid in by_id:
            name, title, slots = by_id[cid]
            bits = ["RP_BTN_%s" % rp[len("RP_BTN_"):] for _, rp, _ in slots]
            bits += ["SLOT_NONE"] * (len(layout.AVRDD_SLOTS) - len(bits))
            names = ", ".join("%s=%s" % (b, pin) for b, _, pin in slots)
            lines.append("    /* %2d %s: %s */" % (cid, title, names))
        else:
            bits = ["RP_BTN_" + b for b in GENERIC]
            lines.append("    /* %2d no board layout yet: generic slot order %s */" % (cid, " ".join(GENERIC)))
        lines.append("    [%d] = {%s}," % (cid, ", ".join(bits)))
    lines += ["};", ""]

    # Console-select board: straps read SELECT_STRAP_ID, select button on PC3,
    # SK6812MINI-E status LED on PC2 (wired by gen_pcb.py build_console_select).
    assert len(layout.CONSOLE_SELECT) == 1, "pinmap.h describes one console-select board"
    (sel_name, sel), = layout.CONSOLE_SELECT.items()
    dim = lambda c: (c * LED_LEVEL + 254) // 255                # status LED, not a torch
    lines += [
        "/* Console-select board (%s): straps read SELECT_STRAP_ID; the select button" % layout.CONSOLES[sel_name][1],
        " * (PC3) steps through select_console[], shown on the status LED (PC2) in GRB. */",
        "#define SELECT_STRAP_ID %d" % layout.SELECT_STRAP_ID,
        "#define SELECT_COUNT %d" % len(sel["consoles"]),
        "static const uint8_t select_console[SELECT_COUNT] = {%s};" % ", ".join(
            "%d /* %s */" % (cid, name) for name, cid in sel["consoles"]),
        "static const uint8_t select_grb[SELECT_COUNT][3] = {%s};" % ", ".join(
            "{%d, %d, %d}" % (dim(g), dim(r), dim(b)) for r, g, b in sel["colours"]),
        "",
        "#endif /* RETROPAD_PINMAP_H */", ""]
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("\n".join(lines))
    print("wrote", os.path.normpath(OUT))


if __name__ == "__main__":
    main()
